### ISSUE TITLE
Prediction at endpoint yields NaN

### ISSUE THREAD

**Issue by Skumin** [JuliaStats/Loess.jl#34] opened 2020-02-13 16:31 UTC
The prediction using `Loess.predict` fails at endpoints for (some) cases where the covariate is equally spaced:

```
using Distributions
import Loess

x = collect(1:50);
y = x .+ rand(Normal(0, 10), 50);

x = convert(Array{Float64}, x);
model = Loess.loess(x, y);
prds = Loess.predict(model, x)
# prds[1] is NaN
```

**Comment by tlnagy** [comment] 2020-04-06 23:28
Duplicate of #28

**Closed by tlnagy** 2020-04-06 23:28 UTC
